stages:
  - build
  - test
  - deploy

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [ gl-code-quality-report.html ]

maven-build:
  image: maven:3.6.3-openjdk-15-slim
  stage: build
  # TODO: create image inherited from maven with installed gnupg
  script:
    - apt update
    - apt install -y gnupg
    - cat $MAVEN_SIGN | base64 -d >> /root/.m2/mvn_sign.key && gpg --batch --import /root/.m2/mvn_sign.key
    - cat $MAVEN_SETTINGS_FILE | base64 -d >> /root/.m2/settings.xml && mvn install --batch-mode
  artifacts:
    paths:
      - target/*.jar

deploy-to-sonatype:
  image: maven:3.6.3-openjdk-15-slim
  stage: deploy
  script:
    - echo "test"
  only:
    - release
