name: Maven CI/CD

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Add GPG sign
        run: echo ${{ secrets.MAVEN_SIGN }} | base64 -d > ~/.m2/mvn_sign.key && gpg --batch --import ~/.m2/mvn_sign.key
      - name: Add maven settings.xml
        run: echo ${{ secrets.MAVEN_SETTINGS_FILE }} | base64 -d > ~/.m2/settings.xml
      - name: Build with Maven
        run: mvn install --batch-mode
      - uses: codecov/codecov-action@v3
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          coverageCommand: mvn test
          coverageLocations: |
            ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
      - name: Deploy to Sonatype
        if: github.ref == 'refs/heads/release'
        run: mvn deploy --batch-mode
